import { router, useLocalSearchParams } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ImageBackground, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import MobileWorkflowHeader from '../components/layout/MobileWorkflowHeader';
import { getLatestPublishedTimetable, getPrincipalTimetableIntelligence } from '../src/services/timetableApi';
import { colors, shadows, spacing } from '../src/theme';
import { PrincipalTimetableIntelligence, TimetablePublishAudit } from '../src/types/timetable';

export default function PrincipalTimetableIntelligenceScreen() {
    const params = useLocalSearchParams();
    const generatedBatchId = String(params.generatedBatchId || 'DEMO');
    const sourceRole = String(params.sourceRole || 'principal');
    const backHome = sourceRole === 'principal' ? '/principal-home' : '/admin-dashboard';
    const [loading, setLoading] = useState(false);
    const [data, setData] = useState<PrincipalTimetableIntelligence | null>(null);
    const [latestPublished, setLatestPublished] = useState<TimetablePublishAudit | null>(null);
    const [status, setStatus] = useState('Loading principal timetable intelligence...');
    useEffect(() => { setLoading(true); Promise.all([getPrincipalTimetableIntelligence(generatedBatchId), getLatestPublishedTimetable().catch(() => null)]).then(([result, latest]) => { setData(result); setLatestPublished(latest); setStatus('Principal intelligence loaded.'); }).catch(() => setStatus('Principal timetable intelligence API unavailable.')).finally(() => setLoading(false)); }, [generatedBatchId]);
    const navParams = { sourceRole, generatedBatchId };
    return <ImageBackground source={require('../assets/branding/splash-gold.png')} style={styles.bg} resizeMode="cover"><ScrollView contentContainerStyle={styles.container}>
        <Header title="Timetable Intelligence" eyebrow="PRINCIPAL VIEW" homePath={backHome} />
        <Text style={styles.status}>{status}</Text><Text style={styles.batch}>Batch: {data?.batchId || generatedBatchId}</Text>{loading ? <ActivityIndicator color={colors.primaryNavy} style={{ marginVertical: 10 }} /> : null}
        <View style={styles.summaryRow}><Kpi label="Readiness" value={`${data?.publishReadinessScore ?? '-'}%`} /><Kpi label="Conflicts" value={String(data?.conflicts ?? '-')} /><Kpi label="Workload" value={String(data?.overloadRiskTeachers ?? '-')} /></View>
        <View style={styles.card}><Text style={styles.big}>{data?.readinessStatus || 'LOADING'}</Text><Text style={styles.text}>Class sections: {data?.classSections ?? '-'}</Text><Text style={styles.text}>Total periods: {data?.totalEntries ?? '-'}</Text><Text style={styles.text}>High risk conflicts: {data?.highRiskConflicts ?? '-'}</Text><Text style={styles.text}>Latest published batch: {latestPublished?.batchId || '-'}</Text><Text style={styles.text}>Latest published at: {latestPublished?.publishedAt || '-'}</Text></View>
        <View style={styles.card}><Text style={styles.cardTitle}>Executive Insights</Text>{(data?.insights || []).map((item, index) => <Text key={index} style={styles.insight}>• {item}</Text>)}</View>
        <View style={styles.card}><Text style={styles.cardTitle}>Top Workload Risks</Text>{(data?.topWorkloadRisks || []).map(item => <View key={item.teacherId} style={styles.riskRow}><Text style={styles.riskName}>{item.teacherName}</Text><Text style={styles.riskScore}>{item.overloadRiskScore}</Text></View>)}</View>
        <TouchableOpacity style={styles.primaryButton} onPress={() => router.push({ pathname: '/timetable-repair' as any, params: navParams })}><Text style={styles.primaryText}>Open Auto Repair</Text></TouchableOpacity>
        <TouchableOpacity style={styles.secondaryButton} onPress={() => router.push({ pathname: '/timetable-publish' as any, params: navParams })}><Text style={styles.secondaryText}>Export / Publish</Text></TouchableOpacity>
    </ScrollView></ImageBackground>;
}
function Header({ title, eyebrow, homePath }: { title: string; eyebrow: string; homePath: string }) { return <MobileWorkflowHeader title={title} eyebrow={eyebrow} homePath={homePath} />; }
function Kpi({ label, value }: { label: string; value: string }) { return <View style={styles.kpi}><Text style={styles.kpiValue}>{value}</Text><Text style={styles.kpiLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ bg:{flex:1}, container:{paddingHorizontal:spacing.lg,paddingTop:72,paddingBottom:32}, headerRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14,gap:8}, circleButton:{width:52,height:52,borderRadius:26,borderWidth:1.5,borderColor:'rgba(255,255,255,0.78)',backgroundColor:'rgba(255,255,255,0.12)',alignItems:'center',justifyContent:'center'}, backText:{color:colors.primaryNavy,fontSize:40,fontWeight:'900',marginTop:-7}, homeIcon:{color:colors.primaryNavy,fontSize:30,fontWeight:'900',marginTop:-3}, headerTextWrap:{flex:1,alignItems:'center'}, eyebrow:{color:colors.deepGold,fontWeight:'900',fontSize:9,letterSpacing:1.5,textAlign:'center'}, title:{color:colors.primaryNavy,fontSize:20,fontWeight:'900',textAlign:'center'}, status:{color:colors.deepGold,fontWeight:'900',marginBottom:5}, batch:{color:colors.slateText,fontWeight:'800',marginBottom:10}, summaryRow:{flexDirection:'row',gap:7,marginBottom:10}, kpi:{flex:1,backgroundColor:colors.cardCream,borderRadius:14,padding:11,borderWidth:1,borderColor:colors.cardGoldBorder,...shadows.soft}, kpiValue:{color:colors.primaryNavy,fontSize:16,fontWeight:'900'}, kpiLabel:{color:colors.mutedText,fontWeight:'800',fontSize:10}, card:{backgroundColor:'rgba(255,253,247,0.96)',borderRadius:20,padding:14,borderWidth:1,borderColor:colors.cardGoldBorder,marginBottom:10,...shadows.medium}, cardTitle:{color:colors.primaryNavy,fontSize:14,fontWeight:'900',marginBottom:8}, big:{color:colors.primaryNavy,fontSize:20,fontWeight:'900',marginBottom:6}, text:{color:colors.slateText,fontWeight:'800',marginBottom:4}, insight:{color:colors.slateText,fontWeight:'700',lineHeight:20,marginBottom:5}, riskRow:{flexDirection:'row',justifyContent:'space-between',paddingVertical:8,borderBottomWidth:1,borderBottomColor:colors.divider}, riskName:{color:colors.primaryNavy,fontWeight:'900'}, riskScore:{color:colors.deepGold,fontWeight:'900'}, primaryButton:{backgroundColor:colors.primaryNavy,borderRadius:13,padding:12,alignItems:'center',marginTop:8}, primaryText:{color:colors.white,fontWeight:'900'}, secondaryButton:{backgroundColor:colors.cardCream,borderRadius:13,padding:12,alignItems:'center',marginTop:8,borderWidth:1,borderColor:colors.cardGoldBorder}, secondaryText:{color:colors.primaryNavy,fontWeight:'900'} });
