import { router, useLocalSearchParams } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ImageBackground, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { exportGeneratedTimetable, getTimetablePublishHistory, publishGeneratedTimetable } from '../src/services/timetableApi';
import { colors, shadows, spacing } from '../src/theme';
import { TimetableExportResponse, TimetablePublishAudit, TimetablePublishResponse } from '../src/types/timetable';

export default function TimetablePublishScreen() {
    const params = useLocalSearchParams();
    const generatedBatchId = String(params.generatedBatchId || 'DEMO');
    const sourceRole = String(params.sourceRole || 'admin');
    const backHome = sourceRole === 'principal' ? '/principal-home' : '/admin-dashboard';
    const [loading, setLoading] = useState(false);
    const [publishResult, setPublishResult] = useState<TimetablePublishResponse | null>(null);
    const [exportResult, setExportResult] = useState<TimetableExportResponse | null>(null);
    const [history, setHistory] = useState<TimetablePublishAudit[]>([]);
    const [status, setStatus] = useState('Review, export, and publish the generated timetable.');
    const loadHistory = () => getTimetablePublishHistory(generatedBatchId).then(setHistory).catch(() => setHistory([]));
    useEffect(() => { loadHistory(); }, [generatedBatchId]);
    const publishNow = () => { setLoading(true); publishGeneratedTimetable(generatedBatchId).then(data => { setPublishResult(data); setStatus(data.message); return loadHistory(); }).catch(() => setStatus('Publish API unavailable.')).finally(() => setLoading(false)); };
    const exportNow = (format: 'PDF' | 'EXCEL') => { setLoading(true); exportGeneratedTimetable(generatedBatchId, format).then(data => { setExportResult(data); setStatus(`${format} export preview ready: ${data.fileName}`); }).catch(() => setStatus('Export API unavailable.')).finally(() => setLoading(false)); };
    return <ImageBackground source={require('../assets/branding/splash-gold.png')} style={styles.bg} resizeMode="cover"><ScrollView contentContainerStyle={styles.container}>
        <Header title="Publish Timetable" eyebrow="PUBLISH WORKFLOW" homePath={backHome} />
        <Text style={styles.status}>{status}</Text><Text style={styles.batch}>Batch: {generatedBatchId}</Text>{loading ? <ActivityIndicator color={colors.primaryNavy} style={{ marginVertical: 10 }} /> : null}
        <View style={styles.card}><Text style={styles.cardTitle}>Publish Status</Text><Text style={styles.big}>{publishResult?.status || (history[0]?.status ?? 'NOT PUBLISHED')}</Text><Text style={styles.text}>Published entries: {publishResult?.publishedEntries ?? history[0]?.publishedEntries ?? 0}</Text><Text style={styles.text}>Remaining conflicts: {publishResult?.remainingConflicts ?? history[0]?.remainingConflicts ?? '-'}</Text><Text style={styles.text}>Approved by: {publishResult?.approvedBy || history[0]?.approvedBy || '-'}</Text><Text style={styles.text}>Published at: {publishResult?.publishedAt || history[0]?.publishedAt || '-'}</Text>{publishResult?.notificationMessage ? <Text style={styles.notice}>{publishResult.notificationMessage}</Text> : null}</View>
        <View style={styles.row}><TouchableOpacity style={styles.secondaryButton} onPress={() => exportNow('EXCEL')}><Text style={styles.secondaryText}>Excel Export</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={() => exportNow('PDF')}><Text style={styles.secondaryText}>PDF Export</Text></TouchableOpacity></View>
        {exportResult ? <View style={styles.card}><Text style={styles.cardTitle}>{exportResult.fileName}</Text><Text numberOfLines={8} style={styles.preview}>{exportResult.content}</Text></View> : null}
        <View style={styles.card}><Text style={styles.cardTitle}>Day 16 Publish Audit History</Text>{history.length === 0 ? <Text style={styles.text}>No publish audit available yet. Publish final timetable to create an audit entry.</Text> : history.map(item => <View key={item.auditId} style={styles.auditRow}><View style={{ flex: 1 }}><Text style={styles.auditTitle}>{item.status} • {item.auditId}</Text><Text style={styles.text}>{item.publishedAt || '-'} • {item.classSections} class sections</Text></View><Text style={styles.auditCount}>{item.publishedEntries}</Text></View>)}</View>
        <TouchableOpacity style={styles.primaryButton} onPress={publishNow}><Text style={styles.primaryText}>Publish Final Timetable</Text></TouchableOpacity>
        <TouchableOpacity style={styles.secondaryFull} onPress={() => router.push({ pathname: '/principal-timetable-intelligence' as any, params: { sourceRole, generatedBatchId } })}><Text style={styles.secondaryText}>Open Principal Intelligence</Text></TouchableOpacity>
    </ScrollView></ImageBackground>;
}
function Header({ title, eyebrow, homePath }: { title: string; eyebrow: string; homePath: string }) { return <View style={styles.headerRow}><TouchableOpacity style={styles.circleButton} onPress={() => router.back()}><Text style={styles.backText}>‹</Text></TouchableOpacity><View style={styles.headerTextWrap}><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text></View><TouchableOpacity style={styles.circleButton} onPress={() => router.replace(homePath as any)}><Text style={styles.homeIcon}>⌂</Text></TouchableOpacity></View>; }
const styles = StyleSheet.create({ bg:{flex:1}, container:{paddingHorizontal:spacing.lg,paddingTop:72,paddingBottom:32}, headerRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:16,gap:7}, circleButton:{width:52,height:52,borderRadius:26,borderWidth:1.5,borderColor:'rgba(255,255,255,0.78)',backgroundColor:'rgba(255,255,255,0.12)',alignItems:'center',justifyContent:'center'}, backText:{color:colors.primaryNavy,fontSize:40,fontWeight:'900',marginTop:-7}, homeIcon:{color:colors.primaryNavy,fontSize:30,fontWeight:'900',marginTop:-3}, headerTextWrap:{flex:1,alignItems:'center'}, eyebrow:{color:colors.deepGold,fontWeight:'900',fontSize:9,letterSpacing:1.5,textAlign:'center'}, title:{color:colors.primaryNavy,fontSize:22,fontWeight:'900',textAlign:'center'}, status:{color:colors.deepGold,fontWeight:'900',marginBottom:5}, batch:{color:colors.slateText,fontWeight:'800',marginBottom:10}, card:{backgroundColor:'rgba(255,253,247,0.96)',borderRadius:20,padding:14,borderWidth:1,borderColor:colors.cardGoldBorder,marginBottom:10,...shadows.medium}, cardTitle:{color:colors.primaryNavy,fontSize:14,fontWeight:'900',marginBottom:8}, big:{color:colors.primaryNavy,fontSize:20,fontWeight:'900',marginBottom:6}, text:{color:colors.slateText,fontWeight:'800',marginBottom:4}, preview:{color:colors.mutedText,fontWeight:'700',lineHeight:18}, notice:{color:colors.deepGold,fontWeight:'900',lineHeight:18,marginTop:6}, auditRow:{flexDirection:'row',alignItems:'center',borderTopWidth:1,borderTopColor:colors.divider,paddingTop:9,marginTop:8}, auditTitle:{color:colors.primaryNavy,fontWeight:'900'}, auditCount:{color:colors.deepGold,fontWeight:'900',fontSize:18}, row:{flexDirection:'row',gap:9,marginBottom:8}, primaryButton:{backgroundColor:colors.primaryNavy,borderRadius:13,padding:12,alignItems:'center',marginTop:8}, primaryText:{color:colors.white,fontWeight:'900'}, secondaryButton:{flex:1,backgroundColor:colors.cardCream,borderRadius:13,padding:12,alignItems:'center',borderWidth:1,borderColor:colors.cardGoldBorder}, secondaryFull:{backgroundColor:colors.cardCream,borderRadius:13,padding:12,alignItems:'center',marginTop:8,borderWidth:1,borderColor:colors.cardGoldBorder}, secondaryText:{color:colors.primaryNavy,fontWeight:'900'} });
